from __future__ import annotations

import locale
import os
import re
import subprocess

DEFAULT_LANGUAGE = "it"

LANGUAGE_NAMES = {
    "it": "Italian",
    "en": "English",
    "fr": "French",
    "de": "German",
    "es": "Spanish",
    "pt": "Portuguese",
    "nl": "Dutch",
}

# Headings and fixed phrases written into published notes, one table per language
# the app offers. Any other language falls back to English headings while the model
# still writes the note body in that language.
LABELS: dict[str, dict[str, str]] = {
    "it": {
        "summary": "Sintesi",
        "overview": "Overview",
        "topics": "Topic",
        "decisions": "Decisioni",
        "action_items": "Action item",
        "open_questions": "Domande aperte",
        "risks": "Rischi",
        "key_concepts": "Concetti chiave",
        "assignments": "Compiti e scadenze",
        "exam_hints": "Per l'esame",
        "review_questions": "Domande di ripasso",
        "references": "Riferimenti",
        "participants": "Partecipanti",
        "speakers_detected": "Speaker rilevati",
        "speaker": "Speaker",
        "me_speaker": "Io",
        "my_notes": "Le mie note",
        "full_transcript": "Transcript completo",
        "classification": "Classificazione",
        "project": "Progetto",
        "course": "Corso",
        "theme": "Tema",
        "details": "Dettagli",
        "summary_provider": "Provider sintesi",
        "transcription": "Trascrizione",
        "audio": "Audio",
        "open_audio": "Ascolta la registrazione",
        "imported_file": "File importato",
        "open_original": "Apri il file originale",
        "slide": "Slide",
        "transcript_by_slide": "Trascrizione per slide",
        "open_slide": "Apri la slide",
        "slides": "Slide",
        "session": "Sessione",
        "subject": "Oggetto",
        "start": "Inizio",
        "end": "Fine",
        "calendar": "Calendario",
        "recording": "Registrazione",
        "calendar_metadata_missing": "Metadata calendario: non trovati",
        "teams_ui_metadata": "Metadata Teams UI",
        "ui_participants": "Partecipanti UI",
        "due": "Scadenza",
        "no_summary": "Nessuna sintesi disponibile.",
        "no_decisions": "Nessuna decisione rilevata.",
        "no_open_questions": "Nessuna domanda aperta rilevata.",
        "no_risks": "Nessun rischio rilevato.",
        "no_action_items": "Nessun action item rilevato.",
        "no_key_concepts": "Nessun concetto chiave rilevato.",
        "no_assignments": "Nessun compito o scadenza rilevato.",
        "no_transcript": "Transcript non disponibile.",
        "no_overview": "Overview non disponibile.",
        "no_metadata": "Metadata meeting non disponibili.",
        "chat_not_found": "Non trovato nei meeting selezionati.",
        "chat_provider_failed": "La chat non ha potuto rispondere: {reason}. Controlla il provider in Impostazioni.",
        "provider_unauthorized": "il provider ha rifiutato la richiesta (chiave API mancante o non valida)",
        "command_failed": "Errore: {reason}.",
        "chat_summary": "Sommario",
        "chat_facts": "Fatti",
        "chat_decisions": "Decisioni",
        "chat_inferences": "Inferenze",
        "chat_empty_section": "Nessun elemento rilevato nei passaggi selezionati.",
        "selected": "selezionato",
        "chat_question": "Domanda",
        "chat_saved": "Salvato",
        "chat_answer": "Risposta",
        "chat_sources": "Fonti",
    },
    "en": {
        "summary": "Summary",
        "overview": "Overview",
        "topics": "Topics",
        "decisions": "Decisions",
        "action_items": "Action items",
        "open_questions": "Open questions",
        "risks": "Risks",
        "key_concepts": "Key concepts",
        "assignments": "Assignments and deadlines",
        "exam_hints": "For the exam",
        "review_questions": "Review questions",
        "references": "References",
        "participants": "Participants",
        "speakers_detected": "Detected speakers",
        "speaker": "Speakers",
        "me_speaker": "Me",
        "my_notes": "My notes",
        "full_transcript": "Full transcript",
        "classification": "Classification",
        "project": "Project",
        "course": "Course",
        "theme": "Topic",
        "details": "Details",
        "summary_provider": "Summary provider",
        "transcription": "Transcription",
        "audio": "Audio",
        "open_audio": "Listen to the recording",
        "imported_file": "Imported file",
        "open_original": "Open the original file",
        "slide": "Slide",
        "transcript_by_slide": "Transcript by slide",
        "open_slide": "Open the slide",
        "slides": "Slides",
        "session": "Session",
        "subject": "Subject",
        "start": "Start",
        "end": "End",
        "calendar": "Calendar",
        "recording": "Recording",
        "calendar_metadata_missing": "Calendar metadata: not found",
        "teams_ui_metadata": "Teams UI metadata",
        "ui_participants": "UI participants",
        "due": "Due",
        "no_summary": "No summary available.",
        "no_decisions": "No decisions detected.",
        "no_open_questions": "No open questions detected.",
        "no_risks": "No risks detected.",
        "no_action_items": "No action items detected.",
        "no_key_concepts": "No key concepts detected.",
        "no_assignments": "No assignments or deadlines detected.",
        "no_transcript": "Transcript not available.",
        "no_overview": "Overview not available.",
        "no_metadata": "Meeting metadata not available.",
        "chat_not_found": "Not found in the selected meetings.",
        "chat_provider_failed": "The chat could not answer: {reason}. Check the provider in Settings.",
        "provider_unauthorized": "the provider rejected the request (missing or invalid API key)",
        "command_failed": "Error: {reason}.",
        "chat_summary": "Summary",
        "chat_facts": "Facts",
        "chat_decisions": "Decisions",
        "chat_inferences": "Inferences",
        "chat_empty_section": "Nothing relevant in the selected passages.",
        "selected": "selected",
        "chat_question": "Question",
        "chat_saved": "Saved",
        "chat_answer": "Answer",
        "chat_sources": "Sources",
    },
    "es": {
        "summary": "Resumen",
        "overview": "Visión general",
        "topics": "Temas",
        "decisions": "Decisiones",
        "action_items": "Acciones",
        "open_questions": "Preguntas abiertas",
        "risks": "Riesgos",
        "key_concepts": "Conceptos clave",
        "assignments": "Tareas y plazos",
        "exam_hints": "Para el examen",
        "review_questions": "Preguntas de repaso",
        "references": "Referencias",
        "participants": "Participantes",
        "speakers_detected": "Hablantes detectados",
        "speaker": "Hablantes",
        "me_speaker": "Yo",
        "my_notes": "Mis notas",
        "full_transcript": "Transcripción completa",
        "classification": "Clasificación",
        "project": "Proyecto",
        "course": "Asignatura",
        "theme": "Tema",
        "details": "Detalles",
        "summary_provider": "Proveedor del resumen",
        "transcription": "Transcripción",
        "audio": "Audio",
        "open_audio": "Escuchar la grabación",
        "imported_file": "Archivo importado",
        "open_original": "Abrir el archivo original",
        "slide": "Diapositiva",
        "transcript_by_slide": "Transcripción por diapositiva",
        "open_slide": "Abrir la diapositiva",
        "slides": "Diapositivas",
        "session": "Sesión",
        "subject": "Asunto",
        "start": "Inicio",
        "end": "Fin",
        "calendar": "Calendario",
        "recording": "Grabación",
        "calendar_metadata_missing": "Metadatos del calendario: no encontrados",
        "teams_ui_metadata": "Metadatos de la interfaz de Teams",
        "ui_participants": "Participantes de la interfaz",
        "due": "Vencimiento",
        "no_summary": "No hay resumen disponible.",
        "no_decisions": "No se han detectado decisiones.",
        "no_open_questions": "No se han detectado preguntas abiertas.",
        "no_risks": "No se han detectado riesgos.",
        "no_action_items": "No se han detectado acciones.",
        "no_key_concepts": "No se han detectado conceptos clave.",
        "no_assignments": "No se han detectado tareas ni plazos.",
        "no_transcript": "Transcripción no disponible.",
        "no_overview": "Visión general no disponible.",
        "no_metadata": "Metadatos de la reunión no disponibles.",
        "chat_not_found": "No se ha encontrado en las reuniones seleccionadas.",
        "chat_provider_failed": "El chat no ha podido responder: {reason}. Revisa el proveedor en Ajustes.",
        "provider_unauthorized": "el proveedor rechazó la solicitud (clave API ausente o no válida)",
        "command_failed": "Error: {reason}.",
        "chat_summary": "Resumen",
        "chat_facts": "Hechos",
        "chat_decisions": "Decisiones",
        "chat_inferences": "Inferencias",
        "chat_empty_section": "Nada relevante en los pasajes seleccionados.",
        "selected": "seleccionado",
        "chat_question": "Pregunta",
        "chat_saved": "Guardado",
        "chat_answer": "Respuesta",
        "chat_sources": "Fuentes",
    },
    "fr": {
        "summary": "Résumé",
        "overview": "Vue d'ensemble",
        "topics": "Thèmes",
        "decisions": "Décisions",
        "action_items": "Actions",
        "open_questions": "Questions ouvertes",
        "risks": "Risques",
        "key_concepts": "Notions clés",
        "assignments": "Devoirs et échéances",
        "exam_hints": "Pour l'examen",
        "review_questions": "Questions de révision",
        "references": "Références",
        "participants": "Participants",
        "speakers_detected": "Locuteurs détectés",
        "speaker": "Locuteurs",
        "me_speaker": "Moi",
        "my_notes": "Mes notes",
        "full_transcript": "Transcription complète",
        "classification": "Classification",
        "project": "Projet",
        "course": "Cours",
        "theme": "Thème",
        "details": "Détails",
        "summary_provider": "Fournisseur du résumé",
        "transcription": "Transcription",
        "audio": "Audio",
        "open_audio": "Écouter l'enregistrement",
        "imported_file": "Fichier importé",
        "open_original": "Ouvrir le fichier d'origine",
        "slide": "Diapositive",
        "transcript_by_slide": "Transcription par diapositive",
        "open_slide": "Ouvrir la diapositive",
        "slides": "Diapositives",
        "session": "Session",
        "subject": "Objet",
        "start": "Début",
        "end": "Fin",
        "calendar": "Calendrier",
        "recording": "Enregistrement",
        "calendar_metadata_missing": "Métadonnées du calendrier : introuvables",
        "teams_ui_metadata": "Métadonnées de l'interface Teams",
        "ui_participants": "Participants de l'interface",
        "due": "Échéance",
        "no_summary": "Aucun résumé disponible.",
        "no_decisions": "Aucune décision détectée.",
        "no_open_questions": "Aucune question ouverte détectée.",
        "no_risks": "Aucun risque détecté.",
        "no_action_items": "Aucune action détectée.",
        "no_key_concepts": "Aucune notion clé détectée.",
        "no_assignments": "Aucun devoir ni échéance détecté.",
        "no_transcript": "Transcription indisponible.",
        "no_overview": "Vue d'ensemble indisponible.",
        "no_metadata": "Métadonnées de la réunion indisponibles.",
        "chat_not_found": "Introuvable dans les réunions sélectionnées.",
        "chat_provider_failed": "Le chat n'a pas pu répondre : {reason}. Vérifiez le fournisseur dans les Réglages.",
        "provider_unauthorized": "le fournisseur a refusé la requête (clé API absente ou invalide)",
        "command_failed": "Erreur: {reason}.",
        "chat_summary": "Résumé",
        "chat_facts": "Faits",
        "chat_decisions": "Décisions",
        "chat_inferences": "Déductions",
        "chat_empty_section": "Rien de pertinent dans les passages sélectionnés.",
        "selected": "sélectionné",
        "chat_question": "Question",
        "chat_saved": "Enregistré",
        "chat_answer": "Réponse",
        "chat_sources": "Sources",
    },
    "de": {
        "summary": "Zusammenfassung",
        "overview": "Überblick",
        "topics": "Themen",
        "decisions": "Entscheidungen",
        "action_items": "Aufgaben",
        "open_questions": "Offene Fragen",
        "risks": "Risiken",
        "key_concepts": "Schlüsselbegriffe",
        "assignments": "Aufgaben und Fristen",
        "exam_hints": "Für die Prüfung",
        "review_questions": "Wiederholungsfragen",
        "references": "Quellen",
        "participants": "Teilnehmende",
        "speakers_detected": "Erkannte Sprecher",
        "speaker": "Sprecher",
        "me_speaker": "Ich",
        "my_notes": "Meine Notizen",
        "full_transcript": "Vollständiges Transkript",
        "classification": "Einordnung",
        "project": "Projekt",
        "course": "Kurs",
        "theme": "Thema",
        "details": "Details",
        "summary_provider": "Anbieter der Zusammenfassung",
        "transcription": "Transkription",
        "audio": "Audio",
        "open_audio": "Aufnahme anhören",
        "imported_file": "Importierte Datei",
        "open_original": "Originaldatei öffnen",
        "slide": "Folie",
        "transcript_by_slide": "Transkript nach Folien",
        "open_slide": "Folie öffnen",
        "slides": "Folien",
        "session": "Sitzung",
        "subject": "Betreff",
        "start": "Beginn",
        "end": "Ende",
        "calendar": "Kalender",
        "recording": "Aufnahme",
        "calendar_metadata_missing": "Kalender-Metadaten: nicht gefunden",
        "teams_ui_metadata": "Teams-UI-Metadaten",
        "ui_participants": "Teilnehmende laut UI",
        "due": "Fällig",
        "no_summary": "Keine Zusammenfassung verfügbar.",
        "no_decisions": "Keine Entscheidungen erkannt.",
        "no_open_questions": "Keine offenen Fragen erkannt.",
        "no_risks": "Keine Risiken erkannt.",
        "no_action_items": "Keine Aufgaben erkannt.",
        "no_key_concepts": "Keine Schlüsselbegriffe erkannt.",
        "no_assignments": "Keine Aufgaben oder Fristen erkannt.",
        "no_transcript": "Transkript nicht verfügbar.",
        "no_overview": "Überblick nicht verfügbar.",
        "no_metadata": "Meeting-Metadaten nicht verfügbar.",
        "chat_not_found": "In den ausgewählten Meetings nicht gefunden.",
        "chat_provider_failed": "Der Chat konnte nicht antworten: {reason}. Prüfe den Anbieter in den Einstellungen.",
        "provider_unauthorized": "der Anbieter hat die Anfrage abgelehnt (API-Schlüssel fehlt oder ist ungültig)",
        "command_failed": "Fehler: {reason}.",
        "chat_summary": "Zusammenfassung",
        "chat_facts": "Fakten",
        "chat_decisions": "Entscheidungen",
        "chat_inferences": "Schlussfolgerungen",
        "chat_empty_section": "Nichts Relevantes in den ausgewählten Passagen.",
        "selected": "ausgewählt",
        "chat_question": "Frage",
        "chat_saved": "Gespeichert",
        "chat_answer": "Antwort",
        "chat_sources": "Quellen",
    },
    "pt": {
        "summary": "Resumo",
        "overview": "Visão geral",
        "topics": "Tópicos",
        "decisions": "Decisões",
        "action_items": "Ações",
        "open_questions": "Perguntas em aberto",
        "risks": "Riscos",
        "key_concepts": "Conceitos-chave",
        "assignments": "Tarefas e prazos",
        "exam_hints": "Para a prova",
        "review_questions": "Perguntas de revisão",
        "references": "Referências",
        "participants": "Participantes",
        "speakers_detected": "Falantes detectados",
        "speaker": "Falantes",
        "me_speaker": "Eu",
        "my_notes": "Minhas notas",
        "full_transcript": "Transcrição completa",
        "classification": "Classificação",
        "project": "Projeto",
        "course": "Disciplina",
        "theme": "Tema",
        "details": "Detalhes",
        "summary_provider": "Provedor do resumo",
        "transcription": "Transcrição",
        "audio": "Áudio",
        "open_audio": "Ouvir a gravação",
        "imported_file": "Arquivo importado",
        "open_original": "Abrir o arquivo original",
        "slide": "Slide",
        "transcript_by_slide": "Transcrição por slide",
        "open_slide": "Abrir o slide",
        "slides": "Slides",
        "session": "Sessão",
        "subject": "Assunto",
        "start": "Início",
        "end": "Fim",
        "calendar": "Calendário",
        "recording": "Gravação",
        "calendar_metadata_missing": "Metadados do calendário: não encontrados",
        "teams_ui_metadata": "Metadados da interface do Teams",
        "ui_participants": "Participantes da interface",
        "due": "Prazo",
        "no_summary": "Nenhum resumo disponível.",
        "no_decisions": "Nenhuma decisão detectada.",
        "no_open_questions": "Nenhuma pergunta em aberto detectada.",
        "no_risks": "Nenhum risco detectado.",
        "no_action_items": "Nenhuma ação detectada.",
        "no_key_concepts": "Nenhum conceito-chave detectado.",
        "no_assignments": "Nenhuma tarefa ou prazo detectado.",
        "no_transcript": "Transcrição indisponível.",
        "no_overview": "Visão geral indisponível.",
        "no_metadata": "Metadados da reunião indisponíveis.",
        "chat_not_found": "Não encontrado nas reuniões selecionadas.",
        "chat_provider_failed": "O chat não conseguiu responder: {reason}. Verifique o provedor em Ajustes.",
        "provider_unauthorized": "o provedor recusou o pedido (chave de API ausente ou inválida)",
        "command_failed": "Erro: {reason}.",
        "chat_summary": "Resumo",
        "chat_facts": "Fatos",
        "chat_decisions": "Decisões",
        "chat_inferences": "Inferências",
        "chat_empty_section": "Nada relevante nos trechos selecionados.",
        "selected": "selecionado",
        "chat_question": "Pergunta",
        "chat_saved": "Salvo",
        "chat_answer": "Resposta",
        "chat_sources": "Fontes",
    },
    "nl": {
        "summary": "Samenvatting",
        "overview": "Overzicht",
        "topics": "Onderwerpen",
        "decisions": "Besluiten",
        "action_items": "Actiepunten",
        "open_questions": "Open vragen",
        "risks": "Risico's",
        "key_concepts": "Kernbegrippen",
        "assignments": "Opdrachten en deadlines",
        "exam_hints": "Voor het tentamen",
        "review_questions": "Herhalingsvragen",
        "references": "Referenties",
        "participants": "Deelnemers",
        "speakers_detected": "Herkende sprekers",
        "speaker": "Sprekers",
        "me_speaker": "Ik",
        "my_notes": "Mijn notities",
        "full_transcript": "Volledig transcript",
        "classification": "Classificatie",
        "project": "Project",
        "course": "Vak",
        "theme": "Onderwerp",
        "details": "Details",
        "summary_provider": "Aanbieder samenvatting",
        "transcription": "Transcriptie",
        "audio": "Audio",
        "open_audio": "Opname beluisteren",
        "imported_file": "Geïmporteerd bestand",
        "open_original": "Origineel bestand openen",
        "slide": "Dia",
        "transcript_by_slide": "Transcript per dia",
        "open_slide": "Dia openen",
        "slides": "Dia's",
        "session": "Sessie",
        "subject": "Onderwerp",
        "start": "Begin",
        "end": "Einde",
        "calendar": "Agenda",
        "recording": "Opname",
        "calendar_metadata_missing": "Agendametadata: niet gevonden",
        "teams_ui_metadata": "Teams-UI-metadata",
        "ui_participants": "Deelnemers volgens UI",
        "due": "Deadline",
        "no_summary": "Geen samenvatting beschikbaar.",
        "no_decisions": "Geen besluiten gevonden.",
        "no_open_questions": "Geen open vragen gevonden.",
        "no_risks": "Geen risico's gevonden.",
        "no_action_items": "Geen actiepunten gevonden.",
        "no_key_concepts": "Geen kernbegrippen gevonden.",
        "no_assignments": "Geen opdrachten of deadlines gevonden.",
        "no_transcript": "Transcript niet beschikbaar.",
        "no_overview": "Overzicht niet beschikbaar.",
        "no_metadata": "Metadata van de vergadering niet beschikbaar.",
        "chat_not_found": "Niet gevonden in de geselecteerde vergaderingen.",
        "chat_provider_failed": "De chat kon niet antwoorden: {reason}. Controleer de provider in Instellingen.",
        "provider_unauthorized": "de provider heeft het verzoek geweigerd (API-sleutel ontbreekt of is ongeldig)",
        "command_failed": "Fout: {reason}.",
        "chat_summary": "Samenvatting",
        "chat_facts": "Feiten",
        "chat_decisions": "Besluiten",
        "chat_inferences": "Afleidingen",
        "chat_empty_section": "Niets relevants in de geselecteerde passages.",
        "selected": "geselecteerd",
        "chat_question": "Vraag",
        "chat_saved": "Opgeslagen",
        "chat_answer": "Antwoord",
        "chat_sources": "Bronnen",
    },
}

NOT_FOUND_ANSWERS = frozenset(labels["chat_not_found"] for labels in LABELS.values())


def normalize_language(value: str | None) -> str | None:
    """'en-IT', 'en_US', 'English' style values -> two-letter code."""
    if not value:
        return None
    match = re.match(r"\s*([A-Za-z]{2})", value)
    return match.group(1).lower() if match else None


def macos_language() -> str | None:
    try:
        result = subprocess.run(
            ["/usr/bin/defaults", "read", "-g", "AppleLanguages"],
            capture_output=True,
            text=True,
            timeout=3,
            check=False,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    match = re.search(r'"?([A-Za-z]{2}[A-Za-z_-]*)"?', result.stdout.replace("(", " "))
    return normalize_language(match.group(1)) if match else None


def resolve_output_language() -> str:
    """OUTPUT_LANGUAGE (set by the app when the user picks a language) wins; otherwise
    follow the macOS language, then the process locale."""
    explicit = normalize_language(os.getenv("OUTPUT_LANGUAGE"))
    if explicit:
        return explicit
    system = macos_language() or normalize_language(locale.getlocale()[0])
    return system or DEFAULT_LANGUAGE


def config_language(config: object) -> str:
    return getattr(config, "output_language", None) or DEFAULT_LANGUAGE


def language_name(code: str) -> str:
    return LANGUAGE_NAMES.get(code, "English")


def label(code: str, key: str) -> str:
    table = LABELS.get(code) or LABELS["en"]
    return table[key]
